name: RDP

on: workflow_dispatch

jobs:
  Windows:

    runs-on: windows-latest
    timeout-minutes: 999999

    steps:
    - name: Установка Ngrok & NSSM
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/AbogusGames/ngrok_rdp/master/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/AbogusGames/ngrok_rdp/master/Files/nssm.exe -OutFile nssm.exe
    - name: Копируем NSSM & Ngrok в папку Windows.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Подключаемся к аккаунту NGROK
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Скачиваем доп.файлы.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/AbogusGames/ngrok_rdp/master/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/AbogusGames/ngrok_rdp/master/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/AbogusGames/ngrok_rdp/master/Files/loop.bat -OutFile loop.bat
    - name: Делаем YML файл для NGROK.
      run: start NGROK-US.bat
    - name: Включаем RDP доступ.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Создаём туннель
      run: sc start ngrok
    - name: Данные для подключения по RDP 2ядра-7GB ОЗУ.
      run: cmd /c NGROK-CHECK.bat
    - name: Всё успешно! You can close Tab now! Максимальное время VM:6ч.
      run: cmd /c loop.bat 
      
    
